###

GET / HTTP/1.1
Host: localhost:9080
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: YWJjZGVmZ2hpag==
Sec-WebSocket-Version: 13

###


###
WEBSOCKET wss://eth-mainnet.ws.alchemyapi.io/ws/demo
Content-Type: application-json

{"jsonrpc":  "2.0", "id": 0, "method":  "eth_gasPrice"}

=== wait-for-server

###

###
WEBSOCKET wss://mainnet.infura.io/ws/v3/d5f208114a764edbac5303f01ea29d19
Content-Type: application-json

{"jsonrpc":  "2.0", "id": 0, "method":  "eth_gasPrice"}

=== wait-for-server

###
